"""empty message

Revision ID: 0de9d201b6ad
Revises: 916493e06e14
Create Date: 2021-08-05 22:46:14.820159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de9d201b6ad'
down_revision = '916493e06e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('travel_range', sa.String(length=150), nullable=True))
    op.drop_column('cars', 'range')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('range', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('cars', 'travel_range')
    # ### end Alembic commands ###
